##---------------------------------------------------------------------
## Datasets:
## wEMspmat£º plant-EM fungal interaction matrix 

#----------------------------------------------------------------------


#-------------------------------------------------------------------
##         relative abundance of EM   
#-------------------------------------------------------------------
       rel.abund.em <-  as.matrix(apply( wEMspmat,2, sum)/sum(wEMspmat))

##--------------------------------------------------------------------------
##        relative abundance of host plants
##--------------------------------------------------------------------------
##  abund213df     # dataframe of abundance of 213 plant species in the HSD forest plot
##
## change "Litsea.rotundifolia.var..oblongifolia" (hsd data) as "Litsea.rotundifolia" (fung.host.data)

      id =  match(  rownames( wEMspmat) , rownames ( abund213df) )   #"Litsea.rotundifolia"
       Host43abund <-   as.data.frame(abund213df[id,])
       rownames( Host43abund) <- rownames(abund213df)[id]
         colnames( Host43abund) <- "plantabund"
###
       rel.abund.host <-  as.matrix( Host43abund/sum(Host43abund[,1]))

###------------------------------------------------------------------------
###           abundance overlap of EM and hosts: Np.web.em
##----------------------------------------------------------------------------
##        EM and host
 
     t.rel.abund.em  <- t(rel.abund.em)
         rel.abund.em.new <- matrix(0,43,1)
           rel.abund.em.new[,1] <- rel.abund.host[,1]
             Np.web.em <- rel.abund.host[,1] %*%  t.rel.abund.em

##--------------------------------------------------------------------
##              spatial overlap for EM fungi and plants:   S.overlap.EM.PL
##---------------------------------------------------------------------------

##  formula:            S = O.p * O.f

      S.overlap.EM.PL <- t(PLquad.mat.bin) %*% (EMquad.mat.bin)

#######    standardized spatital overlaped likelihood matrix

       S.overlap.EM.PL.ses  <-  S.overlap.EM.PL/sum( S.overlap.EM.PL)


###-------------------------------------------------------------------------
###                     Null prob. matrix:  NullEM.pweb
##--------------------------------------------------------------------------
        nr =  nrow(wEMspmat);
        nc = ncol(wEMspmat); 
        NullEM.pweb <-  matrix(1/( nr* nc), nr, nc)

##---------------------------------------------------------------------------
##               observed EM matrix self prob. :   obsEM.pweb
##---------------------------------------------------------------------------
             obsEM.pweb <-   wEMspmat/ sum(wEMspmat)

##--------------------------------------------------------------------------
##              overlaped   Abundance of EM
##-------------------------------------------------------------------------
          Np.web.em   # see above
 


##----------------------------------------------------------------------------           
##              Abund and Spatital interaction
##----------------------------------------------------------------------------
           EM.NandS.pweb <-  Np.web.em * S.overlap.EM.PL
              EM.NandS.pweb.ses <-  EM.NandS.pweb/sum(EM.NandS.pweb)  # standardized 
 
        
##-----------------------------------------------------------------------------------


##------------------------------------------------------------------------------------
##  generate  "netstats" function
##-----------------------------------------------------------------------------------

   netstats  <-  function(imatr,randomize=TRUE,iter= 100,pmatr=NULL){  #iter=1000
       conn = sum(quant2bin(imatr))/(nrow(imatr)*ncol(imatr)) # Connectance
        nest = nested( imatr, method= "weighted NODF" ,rescale=FALSE, normalised=TRUE) # Nestedness
          mod = computeModules(imatr, method="Beckett", deep = FALSE, deleteOriginalFiles = TRUE,
              steps = 1000000, tolerance = 1e-10, experimental = FALSE, forceLPA=FALSE)@likelihood
            even = intereven(imatr) # Interaction eveness
              H2   = H2fun(imatr, H2_integer=TRUE)[[1]]  #specificity
                intas = intasymm(imatr) # Interaction asymmetry
                 # asymm.r = mean(intas$a.r) # Mean asymmetry for plants
                  asymm.c = mean(intas$a.c) # Mean asymmetry for fungi
          
             netstat.o =   c(conn, nest ,mod, even, H2, asymm.r, asymm.c)
             names(netstat.o) = c("conn","nest", "mod", "even","H2","asymm.r","asymm.c")

    imatrsum = sum(imatr)
       netstat.r = matrix (0, iter, 7) # 7, Matrix to store simulation results for each model
       colnames (netstat.r) = c("conn","nest", "mod","even","H2", "asymm.pla","asymm.pol")
       for (it in 1:iter){
           mit = mgen(pmatr,imatrsum, zs = F) # Interaction matrix generated by null model
            conn = sum(quant2bin(mit))/(nrow(mit)*ncol(mit)) # Connectance
             nest= 100-nestedness(mit,null.models=F)$temperature  # Nestedness
             mod = computeModules(mit,method="Beckett", deep = FALSE, deleteOriginalFiles = TRUE,
               steps = 1000000, tolerance = 1e-10, experimental = FALSE, forceLPA=FALSE)@likelihood 
             H2   = H2fun( mit , H2_integer=TRUE)[[1]]
            even = intereven(mit) # Interaction eveness
             intas = intasymm(mit) # Interaction asymmetry
             asymm.r = mean(intas$a.r) # Mean asymmetry for plants
              asymm.c = mean(intas$a.c) # Mean asymmetry for insects
           netstat.r[it,] =   c(conn, nest, mod, even,H2, asymm.r, asymm.c)
          }
      netstat.ci = confint(netstat.r)
       netstat = data.frame(netstat.o, netstat.ci[,1], netstat.ci[,2])
       names(netstat) = c("observed","ci.lo","ci.up")
       netstat
       }

###--------------------------------------------------------------------------------------
##  predict structural metrices of plant-EM network based on propability matrix information
##---------------------------------------------------------------------------------------

   netstats.EM.Np.H2 <-  netstats( wEMspmat, randomize=TRUE,iter=100,pmatr=Np.web.em)

   netstats.EM.Sp.H2 <-  netstats( wEMspmat, randomize=TRUE,iter=100,pmatr= S.overlap.EM.PL.ses)
   netstats.EM.NSp.H2 <-  netstats( wEMspmat, randomize=TRUE,iter=100,pmatr = EM.NandS.pweb.ses)
   netstats.EM.null.H2 <-  netstats( wEMspmat, randomize=TRUE,iter=100,pmatr = NullEM.pweb)

   netstats.EM.obs.H2 <-  netstats( wEMspmat, randomize=TRUE,iter=100, pmatr = obsEM.pweb)


##------------------------------------------------------------------------------------------






















